apiVersion: v1
kind: Service
metadata:
  name: application-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: application-load-balancer-controller
    app.kubernetes.io/part-of: stackit-alb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: application-load-balancer-controller
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
