apiVersion: v1
kind: ServiceAccount
metadata:
  name: application-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: application-load-balancer-controller
    app.kubernetes.io/part-of: stackit-alb
